### PR TITLE
MNT: add HLM, LLM, RDBD to autosave fields as needed for ops

### PR DESCRIPTION
**Pull request by ZLLentz**
@aegger13 noticed that HLM and LLM were not being restored on startup, even though we're restoring DHLM and DLLM. Simple fix is to add HLM and LLM to the autosaveFields.

@jsheppard95 has a script here for resetting his RDBD values on the HOMS mirrors: https://github.com/pcdshub/lcls-plc-lfe-optics/blob/master/set-deadbands.sh, but this should not be necessary, so I've added that field in this PR bundle as well.

### CODE REVIEW

**Review by klauer — APPROVED** [review]
Looks good 👍

**Comment by ZryletTC** [comment]
Aww if I saw this earlier, I would've requested more fields.
I'll do it in a separate PR.

**Comment by klauer** [comment]
D'oh! (Merge/release early, merge/release often?)

**Comment by ZLLentz** [comment]
I tagged you because I figured you'd want more, then I got bored and merged.

Tags are cheap!

**Pull request merged**
