### PR TITLE
Add caputlog

### LINKED ISSUE #29: Add caPutLog support
* Configure to log to logstash
* https://confluence.slac.stanford.edu/display/PCDS/caPutLog+Module

### LINKED ISSUE #48: Add default access security settings
* Required for caPutLog

### PR DESCRIPTION
**Pull request by klauer**
Closes #29 
Closes #48 

~(Waiting on a new caPutLog release from TID prior to merging)~

### CODE REVIEW

**Comment by klauer** [comment]
New caPutLog available and dev log server now available - can finally test this and move forward.

**Comment by klauer** [comment]
No rebasing necessary after #50 fortunately; but prior to merging this we should have a new minor release, pushing this back again as there has been no testing outside of my own.

**Comment by ZLLentz** [comment]
Right, so we tag `R0.2.4` now, then merge this, then test, then tag `R0.3.0`? Or would you like to set aside testing time from me before merging this?

**Comment by klauer** [comment]
That's a good plan. There will assuredly be something to fix from this, but whether it goes in this PR or another does not really matter.

Tagging R0.2.4 as we speak.

**Comment by klauer** [comment]
OK, for testing this, we'll need to generate the IOC but then point it toward the dev log server as the production one has not yet been updated.

`ctl-logdev01` instead of `ctl-logsrv01`

**Comment by ZLLentz** [comment]
Ok, maybe it is time to reopen https://github.com/pcdshub/lcls-twincat-motion-example for business.

**Comment by klauer** [comment]
👍 seems like the perfect candidate!

**Comment by klauer** [comment]
Now waiting on update of production logstash configuration prior to merging + tagging.

Ref: https://github.com/pcdshub/pcds-logstash/pull/12

**Pull request merged**
